// Generated by scripts/generateSharedSchema.mjs. Do not edit.
package io.github.openfinalshell.android.core.protocol

typealias SharedMonitorSnapshot = io.github.openfinalshell.android.core.model.MonitorSnapshot
typealias SharedPortTrafficSnapshot = io.github.openfinalshell.android.core.model.PortTrafficSnapshot
typealias SharedForwardRule = io.github.openfinalshell.android.core.model.ForwardRule
