// Generated by scripts/generateSharedSchema.mjs. Do not edit.
package io.github.openfinalshell.android.core.protocol

object SharedSchemaRegistry {
    val files: Set<String> = setOf("export-envelope", "lansync", "monitor-snapshot", "port-traffic")
}
