import { readFile, writeFile, readdir } from 'node:fs/promises'
import { dirname, resolve, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const schemaDir = resolve(root, 'shared-schema', 'schemas')
const files = (await readdir(schemaDir)).filter((name) => name.endsWith('.json')).sort()
const names = files.map((file) => basename(file, '.schema.json'))
const ts = `// Generated by scripts/generateSharedSchema.mjs. Do not edit.\nexport const SHARED_SCHEMA_FILES = ${JSON.stringify(names)} as const\nexport type SharedSchemaName = typeof SHARED_SCHEMA_FILES[number]\n`
const kt = `// Generated by scripts/generateSharedSchema.mjs. Do not edit.\npackage io.github.openfinalshell.android.core.protocol\n\nobject SharedSchemaRegistry {\n    val files: Set<String> = setOf(${names.map((name) => JSON.stringify(name)).join(', ')})\n}\n`
await writeFile(resolve(root, 'src', 'shared', 'generated', 'sharedSchema.ts'), ts)
await writeFile(resolve(root, 'android', 'core', 'src', 'main', 'kotlin', 'io', 'github', 'openfinalshell', 'android', 'core', 'protocol', 'SharedSchemaRegistry.kt'), kt)
await writeFile(
  resolve(root, 'src', 'shared', 'generated', 'protocolModels.ts'),
  `// Generated by scripts/generateSharedSchema.mjs. Do not edit.\n` +
    `export type { MonitorSnapshot, PortTrafficSnapshot, ForwardRule } from '../types'\n`
)
await writeFile(
  resolve(root, 'android', 'core', 'src', 'main', 'kotlin', 'io', 'github', 'openfinalshell', 'android', 'core', 'protocol', 'GeneratedModels.kt'),
  `// Generated by scripts/generateSharedSchema.mjs. Do not edit.\n` +
    `package io.github.openfinalshell.android.core.protocol\n\n` +
    `typealias SharedMonitorSnapshot = io.github.openfinalshell.android.core.model.MonitorSnapshot\n` +
    `typealias SharedPortTrafficSnapshot = io.github.openfinalshell.android.core.model.PortTrafficSnapshot\n` +
    `typealias SharedForwardRule = io.github.openfinalshell.android.core.model.ForwardRule\n`
)
